---
deployment:
  tasks:
    - export DEPLOYPATH=/home/curr6441/public_html
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp .cpanel.yml $DEPLOYPATH
    - cd $DEPLOYPATH
    - /usr/local/bin/composer install --no-dev --optimize-autoloader
    - /usr/local/bin/php artisan migrate --force
    - /usr/local/bin/php artisan config:cache
    - /usr/local/bin/php artisan route:cache
    - /usr/local/bin/php artisan view:cache
    - /usr/local/bin/php artisan storage:link
